spring:
  application:
    name: service-provider
  rabbitmq:
    host: 192.168.160.128
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka
server:
  port: 8002
config:
  info: config8001-1

