server:
  port: 8080
spring:
  application:
    name: service-customer
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka
#Hystrix的默认超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000  #熔断器超时时间(毫秒)
          timeout:
            enabled: true
# Ribbon的超时设置
ribbon:
  ReadTimeout: 8000  #响应超时(毫秒)
  ConnectTimeout: 5000 #连接超时(毫秒)
#开启feign和hystisx整合
feign:
  hystrix:
    enabled: true
config:
  info: config8080
