spring:
  application:
    name: service-provider
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1
  rabbitmq:
    host: 192.168.160.128
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka
server:
  port: 8001
config:
  info: config8001-1
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"



